GET http://localhost:8080/posts

###
GET http://localhost:8080/posts/2

###
POST http://localhost:8080/posts
Content-Type: application/json

{
    "titulo": "Programando para Backend",
    "texto": "Meu texto",
    "userId": 3
}

###
PUT http://localhost:8080/posts?id=
Content-Type: application/json

{
    "titulo": "Meu título",
    "texto": "Novo texto"
}

###
DELETE http://localhost:8080/posts?id=2