###
GET http://localhost:8080/usuarios

###
GET http://localhost:8080/usuarios/1


###
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "email": "pedro@test.com",
    "senha": "algumasenha"
}

###
PUT http://localhost:8080/usuarios?id=1
Content-Type: application/json

{
    "email": "bananabarco@test.com",
    "senha": "bananabanana"
}

###
DELETE http://localhost:8080/usuarios?id=1
