GET http://localhost:8080

###
GET http://localhost:8080/alunos

###
GET http://localhost:8080/alunos/5d78f8ce-3a39-438f-8f67-b8bc008fc14c


###
POST http://localhost:8080/alunos
Content-Type: application/json

{
    "nome": "Carlos"
}

###
PUT http://localhost:8080/alunos?id=5d78f8ce-3a39-438f-8f67-b8bc008fc14c
Content-Type: application/json

{
    "nome": "Carlos da Silva"
}

###
DELETE http://localhost:8080/alunos?id=5d78f8ce-3a39-438f-8f67-b8bc008fc14c
